framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - de
            - en
            - bg
            - hr
            - da
            - es
            - et
            - fi
            - el
            - hu
            - ga
            - it
            - lv
            - lt
            - mt
            - nl
            - pl
            - pt
            - ro
            - sk
            - sl
            - sv
            - cs
            - ru
            - ua
            - be


