vich_uploader:
    db_driver: orm

    mappings:
        photo:
            uri_prefix: /assets/img/gallery
            upload_destination: '%kernel.project_dir%/public/assets/img/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        categorie:
            uri_prefix: /assets/img/categorie
            upload_destination: '%kernel.project_dir%/public/assets/img/categorie'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true